definitions:
  userapi.LoginParam:
    properties:
      phone:
        type: string
    type: object
info:
  contact: {}
  description: 用户模块接口
  title: user 模块
  version: "1.0"
paths:
  /cmsprovider/v1/message/uploadOffline:
    post:
      description: 上传离线消息
      parameters:
      - description: 离线消息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/userapi.LoginParam'
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 离线消息
swagger: "2.0"
