// Package doc GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package doc

import "github.com/swaggo/swag"

const docTemplateusermod = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cmsprovider/v1/message/uploadOffline": {
            "post": {
                "description": "登录",
                "tags": [
                    "登录"
                ],
                "parameters": [
                    {
                        "description": "离线消息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userapi.LoginParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.User": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "img": {
                    "description": "头像图片",
                    "type": "string"
                },
                "inviter_id": {
                    "description": "邀请人ID",
                    "type": "string"
                },
                "lang": {
                    "description": "语言",
                    "type": "string"
                },
                "name": {
                    "description": "名字",
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "peerId": {
                    "description": "peerId",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "profile": {
                    "description": "个人简介",
                    "type": "string"
                },
                "ptime": {
                    "description": "时间",
                    "type": "integer"
                },
                "role": {
                    "description": "角色 1 人工客服  2 普通用户",
                    "type": "string"
                },
                "sex": {
                    "description": "性别 0 未知 1 男 2 女",
                    "type": "integer"
                },
                "status": {
                    "description": "状态（0启用 -1禁用）",
                    "type": "integer"
                },
                "utime": {
                    "description": "时间",
                    "type": "integer"
                }
            }
        },
        "userapi.LoginParam": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfousermod holds exported Swagger Info so clients can modify it
var SwaggerInfousermod = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "user 模块",
	Description:      "用户模块接口",
	InfoInstanceName: "usermod",
	SwaggerTemplate:  docTemplateusermod,
}

func init() {
	swag.Register(SwaggerInfousermod.InstanceName(), SwaggerInfousermod)
}
