definitions:
  model.User:
    properties:
      id:
        description: id
        type: string
      img:
        description: 头像图片
        type: string
      inviter_id:
        description: 邀请人ID
        type: string
      lang:
        description: 语言
        type: string
      name:
        description: 名字
        type: string
      nickname:
        description: 昵称
        type: string
      peerId:
        description: peerId
        type: string
      phone:
        description: 手机号
        type: string
      profile:
        description: 个人简介
        type: string
      ptime:
        description: 时间
        type: integer
      role:
        description: 角色 1 人工客服  2 普通用户
        type: string
      sex:
        description: 性别 0 未知 1 男 2 女
        type: integer
      status:
        description: 状态（0启用 -1禁用）
        type: integer
      utime:
        description: 时间
        type: integer
    type: object
  userapi.LoginParam:
    properties:
      phone:
        type: string
    type: object
info:
  contact: {}
  description: 用户模块接口
  title: user 模块
  version: "1.0"
paths:
  /cmsprovider/v1/message/uploadOffline:
    post:
      description: 登录
      parameters:
      - description: 离线消息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/userapi.LoginParam'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      tags:
      - 登录
swagger: "2.0"
